name: ci-platform-kong-oidc

on:
  push:
    branches: [ "main" ]
    paths:
      - 'gateway/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'gateway/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up QEMU for multi-architecture Docker builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub using secrets
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Kong OIDC Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./gateway            
          file: Dockerfile               
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/platform.kong-oidc:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/platform.kong-oidc:${{ github.run_number }}
